spring.application.name=spring-ecommerce

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:database

jwt.secret-key=X1yk3dV+NQemyyJbg6WzioaRR1NArxZxjMvvroTZauk=
jwt.expiration-ms=3600000

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create

spring.jpa.defer-datasource-initialization=true

logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.beans.factory=debug

stripe.secret-key=${STRIPE_SECRET_KEY}
