INSERT INTO products (name, price, image_url) VALUES ('Iron Man', 1000, 'https://alexnsan.comics/imageurl/1');
INSERT INTO products (name, price, image_url) VALUES ('X-men', 1000, 'https://alexnsan.comics/imageurl/2');
INSERT INTO products (name, price, image_url) VALUES ('Superman', 1000, 'https://alexnsan.comics/imageurl/3');
INSERT INTO products (name, price, image_url) VALUES ('Naruto', 1000, 'https://alexnsan.comics/imageurl/4');
INSERT INTO products (name, price, image_url) VALUES ('Full Metal Alchemist', 1000, 'https://alexnsan.comics/imageurl/5');
INSERT INTO products (name, price, image_url) VALUES ('Batman', 1000, 'https://alexnsan.comics/imageurl/6');
INSERT INTO products (name, price, image_url) VALUES ('Man', 1000, 'https://alexnsan.comics/imageurl/7');
;
INSERT INTO options (name, quantity, product_id) VALUES ('small', 10, 1);
INSERT INTO options (name, quantity, product_id) VALUES ('medium', 20, 1);
INSERT INTO options (name, quantity, product_id) VALUES ('large', 30, 1);
INSERT INTO options (name, quantity, product_id) VALUES ('small', 10, 2);
INSERT INTO options (name, quantity, product_id) VALUES ('medium', 20, 2);
INSERT INTO options (name, quantity, product_id) VALUES ('large', 30, 2);
INSERT INTO options (name, quantity, product_id) VALUES ('small', 10, 3);
INSERT INTO options (name, quantity, product_id) VALUES ('medium', 20, 3);
INSERT INTO options (name, quantity, product_id) VALUES ('large', 30, 3);
INSERT INTO options (name, quantity, product_id) VALUES ('small', 10, 4);
INSERT INTO options (name, quantity, product_id) VALUES ('medium', 20, 4);
INSERT INTO options (name, quantity, product_id) VALUES ('large', 30, 4);
INSERT INTO options (name, quantity, product_id) VALUES ('small', 10, 5);
INSERT INTO options (name, quantity, product_id) VALUES ('medium', 20, 5);
INSERT INTO options (name, quantity, product_id) VALUES ('large', 30, 5);
INSERT INTO options (name, quantity, product_id) VALUES ('small', 10, 6);
INSERT INTO options (name, quantity, product_id) VALUES ('medium', 20, 6);
INSERT INTO options (name, quantity, product_id) VALUES ('small', 10, 7);
;
INSERT INTO carts () VALUES ();
INSERT INTO carts () VALUES ();
INSERT INTO carts () VALUES ();
INSERT INTO carts () VALUES ();
;
INSERT INTO members (email, password, role, cart_id) VALUES ( 'san@htc.com', 'san1234', 'admin', 1);
INSERT INTO members (email, password, role, cart_id) VALUES ( 'dan@htc.com', 'dan1234', 'admin', 2);
INSERT INTO members (email, password, cart_id) VALUES ( 'ann@htc.com', 'ann1234', 3);
INSERT INTO members (email, password, cart_id) VALUES ( 'min@htc.com', 'min1234', 4);
;
INSERT INTO cart_items (member_id, product_id, option_id, quantity, created_at, cart_id) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP - INTERVAL '5' DAY, 1);
INSERT INTO cart_items (member_id, product_id, option_id, quantity, created_at, cart_id) VALUES (1, 2, 1, 1, CURRENT_TIMESTAMP - INTERVAL '3' DAY, 1);
INSERT INTO cart_items (member_id, product_id, option_id, quantity, created_at, cart_id) VALUES (2, 2, 1, 1, CURRENT_TIMESTAMP - INTERVAL '2' DAY, 2);
INSERT INTO cart_items (member_id, product_id, option_id, quantity, created_at, cart_id) VALUES (3, 2, 2, 1, CURRENT_TIMESTAMP - INTERVAL '1' DAY, 3);
INSERT INTO cart_items (member_id, product_id, option_id, quantity, created_at, cart_id) VALUES (1, 3, 1, 1, CURRENT_TIMESTAMP - INTERVAL '10' DAY, 1);
INSERT INTO cart_items (member_id, product_id, option_id, quantity, created_at, cart_id) VALUES (2, 3, 2, 1, CURRENT_TIMESTAMP - INTERVAL '20' DAY, 2);
INSERT INTO cart_items (member_id, product_id, option_id, quantity, created_at, cart_id) VALUES (3, 3, 1, 1, CURRENT_TIMESTAMP - INTERVAL '25' DAY, 3);
INSERT INTO cart_items (member_id, product_id, option_id, quantity, created_at, cart_id) VALUES (1, 4, 1, 1, CURRENT_TIMESTAMP - INTERVAL '6' DAY, 1);
INSERT INTO cart_items (member_id, product_id, option_id, quantity, created_at, cart_id) VALUES (2, 5, 3, 1, CURRENT_TIMESTAMP - INTERVAL '7' DAY, 2);
INSERT INTO cart_items (member_id, product_id, option_id, quantity, created_at, cart_id) VALUES (3, 5, 1, 1, CURRENT_TIMESTAMP - INTERVAL '8' DAY, 3);
INSERT INTO cart_items (member_id, product_id, option_id, quantity, created_at, cart_id) VALUES (1, 5, 1, 1, CURRENT_TIMESTAMP - INTERVAL '9' DAY, 1);
INSERT INTO cart_items (member_id, product_id, option_id, quantity, created_at, cart_id) VALUES (1, 6, 1, 1, CURRENT_TIMESTAMP - INTERVAL '6' DAY, 1);
INSERT INTO cart_items (member_id, product_id, option_id, quantity, created_at, cart_id) VALUES (2, 6, 1, 1, CURRENT_TIMESTAMP - INTERVAL '7' DAY, 2);
INSERT INTO cart_items (member_id, product_id, option_id, quantity, created_at, cart_id) VALUES (3, 3, 2, 1, CURRENT_TIMESTAMP - INTERVAL '8' DAY, 3);
INSERT INTO cart_items (member_id, product_id, option_id, quantity, created_at, cart_id) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP - INTERVAL '9' DAY, 1);
;
